In [1]:
import os
import sys
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import plot_confusion_matrix
import matplotlib.pyplot as plt
from sklearn.model_selection import cross_val_score
from joblib import dump
# from models import eval_model
from sklearn.preprocessing import StandardScaler
%load_ext autoreload
%autoreload 2

In [2]:
from src.models import eval_model

In [34]:
x_train = np.load('../data/processed/X_train.npy')
y_train  = np.load('../data/processed/y_train.npy' )

x_test = np.load('../data/processed/x_test.npy')
y_test = np.load('../data/processed/y_test.npy' )

x_val = np.load('../data/processed/x_val.npy')
y_val  = np.load('../data/processed/y_val.npy' )

In [6]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(x_train,y_train)

In [7]:
def eval_model(mod, xvar, yvar,runtype):

  from sklearn.metrics import accuracy_score, confusion_matrix,roc_curve, roc_auc_score, precision_score, recall_score, precision_recall_curve, f1_score, plot_confusion_matrix
  import matplotlib.pyplot as plt
  


  mod_pred_proba =mod.predict(xvar)
  mod_pred = mod_pred_proba.round()
  print('Accuracy Score ',accuracy_score(yvar,mod_pred),' F1 Score ',f1_score(yvar,mod_pred), ' R2 Score ',mod.score(xvar, yvar),' ROC_AUC_SCORE ',roc_auc_score(yvar, mod_pred_proba),'(',runtype,')')
  print(f'Recall score: {recall_score(yvar,mod_pred)}')
#   disp = plot_confusion_matrix(mod, xvar, yvar, cmap=plt.cm.Blues)
#   disp.ax_.set_title('Confusion matrix '+runtype)
  return


In [8]:
eval_model(reg,x_train,y_train,"Train")
eval_model(reg,x_val,y_val,"Val")

Accuracy Score  0.837890625  F1 Score  0.9117021276595746  R2 Score  0.07717937323159862  ROC_AUC_SCORE  0.7068695020651701 ( Train )
Recall score: 0.9997666822211853
Accuracy Score  0.838125  F1 Score  0.911934716082965  R2 Score  0.06803722021581693  ROC_AUC_SCORE  0.7054999116328795 ( Val )
Recall score: 0.9985107967237528


In [9]:
eval_model(reg,x_test,y_test,"Test")

Accuracy Score  0.81171875  F1 Score  0.8960758947822338  R2 Score  0.07151438080141692  ROC_AUC_SCORE  0.6966025641025642 ( Test )
Recall score: 0.9990384615384615


In [10]:
from sklearn.linear_model import LinearRegression

def calculateVIF(data):
    features = list(data.columns)
    num_features = len(features)

    model = LinearRegression()

    result = pd.DataFrame(index = ['VIF'], columns = features)
    result = result.fillna(0)

    for ite in range(num_features):
        x_features = features[:]
        y_featue = features[ite]
        x_features.remove(y_featue)

        x = data[x_features]
        y = data[y_featue]

        model.fit(data[x_features], data[y_featue])

        result[y_featue] = 1/(1 - model.score(data[x_features], data[y_featue]))

    return result

In [15]:
df=pd.read_csv('../data/raw/train.csv')
df_cleaned = df.drop(['Id_old','Id'],axis=1)
x=df_cleaned.drop('TARGET_5Yrs',axis=1)

In [16]:
calculateVIF(x)

GP        MIN         PTS         FGM         FGA       FG%  \
VIF  1.714412  13.397745  248.284029  199.075827  100.861373  5.812264   

       3P Made       3PA       3P%        FTM       FTA       FT%      OREB  \
VIF  29.939912  31.58869  1.778763  77.284367  63.82767  3.265819  22.26328   

          DREB         REB       AST       STL       BLK       TOV  
VIF  72.532674  144.136923  4.416166  3.384907  1.330506  5.764583

In [17]:
x = x.drop(['PTS'], axis=1)
calculateVIF(x)

GP        MIN         FGM        FGA       FG%    3P Made  \
VIF  1.710919  13.344454  101.070211  93.269887  5.609194  29.415186   

           3PA       3P%        FTM        FTA       FT%       OREB  \
VIF  31.568854  1.747469  66.560465  63.821399  3.259018  22.235323   

          DREB         REB       AST       STL       BLK       TOV  
VIF  72.373889  144.005474  4.405789  3.384853  1.329888  5.751933

In [18]:
x = x.drop(['REB'], axis=1)
calculateVIF(x)

GP        MIN         FGM        FGA       FG%    3P Made  \
VIF  1.710851  13.334696  100.469945  92.932881  5.589226  29.413284   

           3PA       3P%        FTM        FTA       FT%      OREB      DREB  \
VIF  31.545257  1.737265  66.173494  63.333286  3.255216  4.141201  5.554398   

          AST       STL       BLK      TOV  
VIF  4.396603  3.376394  1.328888  5.69345

In [19]:
x = x.drop(['FGM'], axis=1)
calculateVIF(x)

GP        MIN       FGA       FG%    3P Made        3PA      3P%  \
VIF  1.70308  13.333276  7.390854  1.810382  29.311514  31.391071  1.73329   

           FTM        FTA       FT%      OREB      DREB       AST       STL  \
VIF  66.045074  63.039714  3.242674  4.118947  5.545526  4.394019  3.376134   

          BLK      TOV  
VIF  1.328105  5.69246

In [20]:
x = x.drop(['FTM'], axis=1)
calculateVIF(x)

GP        MIN       FGA       FG%    3P Made       3PA       3P%  \
VIF  1.700425  13.319159  7.317016  1.810219  29.308158  31.37767  1.730677   

          FTA       FT%      OREB      DREB       AST       STL       BLK  \
VIF  3.868517  1.324642  4.081037  5.542246  4.392643  3.375625  1.327203   

          TOV  
VIF  5.692099

In [21]:
x = x.drop(['3P Made'], axis=1)
calculateVIF(x)

GP        MIN       FGA       FG%       3PA       3P%       FTA  \
VIF  1.698264  13.277574  7.229271  1.646459  2.185307  1.666908  3.864032   

          FT%      OREB      DREB       AST      STL       BLK      TOV  
VIF  1.324479  4.080885  5.542239  4.390932  3.33343  1.326198  5.68571

In [22]:
x = x.drop(['MIN'], axis=1)
calculateVIF(x)

GP       FGA       FG%       3PA       3P%       FTA       FT%  \
VIF  1.663796  5.313572  1.626013  2.097974  1.666896  3.848178  1.316268   

         OREB      DREB       AST       STL       BLK       TOV  
VIF  4.080823  3.756681  4.066983  2.938353  1.324961  5.661401

In [23]:
y=df_cleaned['TARGET_5Yrs']
x_data , x_val ,y_data,  y_val = train_test_split(x, y, test_size=0.2, random_state = 8)
x_train , x_test , y_train, y_test = train_test_split(x_data, y_data, test_size=0.2, random_state = 8)

In [25]:
reg1 = LinearRegression().fit(x_train,y_train)
eval_model(reg1,x_train,y_train,"Train")
eval_model(reg1,x_val,y_val,"Val")

Accuracy Score  0.8373046875  F1 Score  0.9114300903774588  R2 Score  0.07305197907549166  ROC_AUC_SCORE  0.7040411534514806 ( Train )
Recall score: 1.0
Accuracy Score  0.83875  F1 Score  0.912304554724677  R2 Score  0.06935791889869525  ROC_AUC_SCORE  0.7084870100332898 ( Val )
Recall score: 0.9992553983618764


In [27]:
eval_model(reg1,x_test,y_test,"Test")

Accuracy Score  0.8125  F1 Score  0.896551724137931  R2 Score  0.06787826531303431  ROC_AUC_SCORE  0.6946674679487179 ( Test )
Recall score: 1.0


In [29]:
y_pred_prob=reg1.predict(x_test)

In [31]:
np.unique(y_pred_prob.round(),return_counts=True)

(array([1.]), array([1280], dtype=int64))

In [37]:
y_pred_prob1

array([0.61763669, 0.8107596 , 0.84515334, ..., 0.88608879, 0.87291382,
       0.95446562])

In [35]:
y_pred_prob1=reg.predict(x_test)

In [36]:
np.unique(y_pred_prob1.round(),return_counts=True)

(array([0., 1.]), array([   1, 1279], dtype=int64))

# Test Result

In [39]:
df_test=pd.read_csv('../data/raw/test.csv')
df_actual_test_cleaned = df_test.drop(['Id_old', 'Id', 'PTS', 'REB', 'FGM', 'FTM', '3P Made', 'MIN'], axis=1)


In [41]:
y_actual_test_pred_prob=reg1.predict(df_actual_test_cleaned)

In [42]:
np.unique(y_actual_test_pred_prob,return_counts=True)

(array([0.536719  , 0.53939556, 0.54168588, ..., 1.19617731, 1.2086856 ,
        1.20954182]),
 array([1, 1, 1, ..., 1, 1, 1], dtype=int64))

In [43]:
np.unique(y_actual_test_pred_prob.round(),return_counts=True)

(array([1.]), array([3799], dtype=int64))

In [40]:
y_actual_test_pred_prob[y_actual_test_pred_prob>1]=1

In [41]:
np.unique(y_actual_test_pred_prob,return_counts=True)

(array([0.45837117, 0.50122072, 0.51821311, ..., 0.9992085 , 0.99931308,
        1.        ]),
 array([  1,   1,   1, ...,   1,   1, 181], dtype=int64))

In [42]:
df_test['TARGET_5Yrs'] = y_actual_test_pred_prob

In [43]:
df_test.to_csv('./kaggle_assignment/data/processed/TestResult_Reg1.csv',index=False,columns=['Id', 'TARGET_5Yrs'])

# Cross Val Pred

In [47]:
y_actual_test_pred_prob1=reg2.predict(df_actual_test_cleaned)

NotFittedError: This LinearRegression instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.